"""Tabs"""
REPAIR_TAB = (1805, 70, 80, 10)

"""Buttons"""
MAKE_BUTTON = (646, 525, 64, 14)
MAKE_ALL_BUTTON = (722, 526, 62, 12)
REPAIR_ALL_BUTTON = (1750, 450, 60, 10)

"""Other Controls"""
QUANTITY_INCREMENT_ARROW = (624, 526, 6, 6)

"""Skills Keys"""

"""NPC Interactions"""
BROWSE_THE_SHOP_RECT = (22, 330, 165, 15)

"""Character Buffs"""
HARVESTING_INDUCTION_REDUCTION_BUFF = 3

"""Inductions"""
COOKING_INGREDIENT_INDUCTION = 2.987
PROCESSING_CROP_INDUCTION = 5.01
PLANTING_CROP_INDUCTION = 3.3
HARVESTING_CROP_INDUCTION = 8 - HARVESTING_INDUCTION_REDUCTION_BUFF

"""Recipes"""
GUNDABAD_FIELD_RECIPE = (35, 432, 120, 10)

"""Hotkeys"""
SELECT_NEAREST_ITEM_HOTKEY = ['ctrl', 'alt', 'i']
SELECT_NEXT_ITEM_HOTKEY = ['ctrl', 'shift', 'i']
SELECT_NEAREST_NPC_HOTKEY = ['ctrl', 'alt', 'n']
SELECT_NEXT_NPC_HOTKEY = ['ctrl', 'shift', 'n']

"""Keys"""
USE_SELECTION_KEY = 'u'
MOVE_FORWARD_KEY = 'e'
MOVE_BACKWARD_KEY = 'd'
TURN_LEFT_KEY = 's'
TURN_RIGHT_KEY = 'r'

"""Datetime Formats"""
TODAY_FORMAT = r'%Y_%m_%d'
TIMESTAMP_FORMAT = r'%H_%M_%S_%f'

"""Logging"""
DEFAULT_LOG_LEVEL = 'INFO'
DEFAULT_LOG_DIRECTORY = 'C:/lotro-bot-logs'

"""System"""
LOTRO_WINDOW_NAME = 'The Lord of the Rings Online™'
